version: '3.8'

services:
  postgres:
    image: postgres:alpine
    container_name: twt-pg
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - my_pgdata:/var/lib/postgresql/data

volumes:
  my_pgdata:

