import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import { Viewport } from "next";

export const metadata: Metadata = {
  title: "twt Ai",
  description: "Mood wise Tweet generated by Ai",
};

export const viewport: Viewport={
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light" >
      <body>
        <NavBar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
