import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/layout/Footer";
import NavBar from "@/components/layout/NavBar";
import { Toaster } from "@/components/ui/toaster";
import type { Viewport } from "next";
import UserContextProvider from "./context/UserContext";

export const metadata: Metadata = {
	title: "twt Ai",
	description: "Mood wise Tweet generated by Ai",
};

export const viewport: Viewport = {
	width: "device-width",
	initialScale: 1,
	maximumScale: 1,
	userScalable: false,
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="light">
			<body className="flex flex-col justify-between min-h-screen">
				<UserContextProvider>
					<NavBar />
					{children}
					<Footer />
					<Toaster />
				</UserContextProvider>
			</body>
		</html>
	);
}
